# action.yml
name: 'Autodocs'
description: 'Automated reference documentation for Chainguard projects'
author: 'The Developer Education team at Chainguard'
branding:
  icon: 'document'
  color: 'purple'
inputs:
  template:
    description: 'Cover template to Use'
    required: false
    default: 'cover_basic.json'
outputs:
  response:
    description: 'Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
