#!/usr/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use App\Service\AutodocsService;
use App\Service\CacheService;
use App\Service\ImageDiscoveryService;
use Minicli\App;
use Minicli\Exception\CommandNotFoundException;
use Yamldocs\YamldocsConfig;

$config = new YamldocsConfig();
$config->load(__DIR__ . '/yamldocs.yaml');
$app = new App(array_merge([
    'app_path' => [
        __DIR__ . '/app/Command',
        '@minicli/command-help'
    ]
], $config->parameters));

$app->addService('builder', new AutodocsService());
$app->addService('imageDiscovery', new ImageDiscoveryService());
$app->addService('cache', new CacheService());
$app->setSignature('./autodocs help');

$input = $argv;
//check for workflow inputs
if (getenv('INPUT_COMMAND')) {
    $input = array_merge(['autodocs'], explode(' ', getenv('INPUT_COMMAND')));
}
try {
    $app->runCommand($input);
} catch (CommandNotFoundException $notFoundException) {
    $app->error("Command Not Found.");
    return 1;
} catch (Exception $exception) {
    if ($app->config->debug) {
        $app->error("An error occurred:");
        $app->error($exception->getMessage());
    }
    return 1;
}

return 0;