name: Test Workflow for Images Reference Docs

on:
  workflow_dispatch:

env:
  WORKDIR: images-reference
<<<<<<< HEAD

=======
>>>>>>> 83e9fe6 (updated example workflow)
jobs:
  main:
    runs-on: ubuntu-latest
    outputs:
      build-output: ${{ steps.images-build-output.changelog }}
    steps:
      - name: "Check out Destination Repo"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          path: autodocs

      - name: "Check out Images Monorepo"
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          repository: chainguard-images/images
          path: images

      - name: "Set up workdir"
        run: |
          mkdir -p "${{ github.workspace }}/${{ env.WORKDIR }}" && \
          chmod 777 "${{ github.workspace }}/${{ env.WORKDIR }}"

      - name: "Update the reference docs for Chainguard Images"
<<<<<<< HEAD
        uses: chainguard-dev/deved-autodocs@37cc961b71c9b6c1eaf4e0ad5f2e5a66ba94918c # 1.3.6
=======
        uses: chainguard-dev/deved-autodocs@1.3.6
>>>>>>> 28ad5b7 (Updated changelog build to use custom source path)
        with:
          command: build images
        env:
          YAMLDOCS_SOURCE: "${{ github.workspace }}/images/images"
          YAMLDOCS_OUTPUT: "${{ github.workspace }}/${{ env.WORKDIR }}"
          YAMLDOCS_TEMPLATES: "${{ github.workspace }}/autodocs/workdir/templates"
          YAMLDOCS_CHANGELOG: "${{ github.workspace }}/${{ env.WORKDIR }}/changelog.md"
          YAMLDOCS_LAST_UPDATE: "${{ github.workspace }}/${{ env.WORKDIR }}/last-update.md"
          YAMLDOCS_DIFF_SOURCE: "${{ github.workspace }}/autodocs/workdir/{{ env.WORKDIR }}"

      - name: "Copy changelog to root folder"
        run: |
          mv "${{ github.workspace }}/${{ env.WORKDIR }}/changelog.md" \
          "${{ github.workspace }}/${{ env.WORKDIR }}/last-update.md" \
          "${{ github.workspace }}/autodocs"

      - name: "Copy updates to main repo"
        run: |
          echo "Copying files..." && \
          cp -R "${{ github.workspace }}/${{ env.WORKDIR }}" "${{ github.workspace }}/autodocs/workdir" && \
          echo "Finished copy"

      - name: "Get Changelog"
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "CHANGELOG<<$EOF" >> $GITHUB_ENV
          echo "`cat ${{ github.workspace }}/autodocs/last-update.md`" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV
        id: images-build-output

      - name: Create a PR
        id: cpr
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          path: "${{ github.workspace }}/autodocs"
          commit-message: Update Images Reference
          title: "[AutoDocs] Update Images Reference Docs"
          body: "${{ env.CHANGELOG }}"
          signoff: true
          labels: |
            documentation
            images
            automated
          assignees: erikaheidi

      - name: "Send notification to Slack"
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: chainguard-dev/deved-autodocs@37cc961b71c9b6c1eaf4e0ad5f2e5a66ba94918c # 1.3.6
        with:
          command: notify pullrequest
        env:
          AUTODOCS_SLACK_PRIMARY: ${{ secrets.AUTODOCS_SLACK_PRIMARY }}
          AUTODOCS_SLACK_SECONDARY: ${{ secrets.AUTODOCS_SLACK_SECONDARY }}
          AUTODOCS_SLACK_GENERAL: ${{ secrets.AUTODOCS_SLACK_GENERAL }}
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
          PR_ACTION: ${{ steps.cpr.outputs.pull-request-operation }}
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          PR_SHA: ${{ steps.cpr.outputs.pull-request-head-sha }}
<<<<<<< HEAD
          PR_SUMMARY: ${{ env.CHANGELOG }}
=======
          PR_SUMMARY: ${{ env.CHANGELOG }}
>>>>>>> 28ad5b7 (Updated changelog build to use custom source path)
