name: Test Workflow for Images Reference Docs
on:
  workflow_dispatch:
env:
  WORKDIR: images-reference
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Destination Repo"
        uses: actions/checkout@v2
        with:
          path: autodocs

      - name: "Check out Images Monorepo"
        uses: actions/checkout@v2
        with:
          repository: chainguard-images/images
          path: images

      - name: "Set up workdir"
        run: mkdir -p "${{ github.workspace }}/${{ env.WORKDIR }}" && chmod 777 "${{ github.workspace }}/${{ env.WORKDIR }}"

      - name: "Update the reference docs for Chainguard Images"
        uses: chainguard-dev/deved-autodocs@1.0.2
        with:
          command: build images
        env:
          YAMLDOCS_SOURCE: "${{ github.workspace }}/images/images"
          YAMLDOCS_OUTPUT: "${{ github.workspace }}/${{ env.WORKDIR }}"

      - name: "Copy updates to main repo"
        run: |
          ls "${{ github.workspace }}/${{ env.WORKDIR }}" && \
          echo "Copying files..." && \
          cp -R "${{ github.workspace }}/${{ env.WORKDIR }}" "${{ github.workspace }}/autodocs/workdir" && \
          echo "Finished copy" 

      - name: "Debug content dir"
        run: |
          ls "${{ github.workspace }}/autodocs/workdir/${{ env.WORKDIR }}"

      - name: Create a PR
        uses: peter-evans/create-pull-request@v4
        with:
          path: "${{ github.workspace }}/autodocs"
          commit-message: Update Images Reference
          title: "[automated] Update Images Reference Docs"
