name: Send Slack Notification about new Autodocs PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  main:
    if: startsWith(github.head_ref, 'create-pull-request/')
    runs-on: ubuntu-latest
    steps:
      - name: "Send notification to Slack"
        uses: chainguard-dev/deved-autodocs@37cc961b71c9b6c1eaf4e0ad5f2e5a66ba94918c # 1.3.6
        with:
          command: notify pullrequest
        env:
          AUTODOCS_SLACK_PRIMARY: ${{ secrets.AUTODOCS_SLACK_PRIMARY }}
          AUTODOCS_SLACK_SECONDARY: ${{ secrets.AUTODOCS_SLACK_SECONDARY }}
          AUTODOCS_SLACK_GENERAL: ${{ secrets.AUTODOCS_SLACK_GENERAL }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_CHANGED: ${{ github.event.pull_request.changed_files }}
          PR_STATE: ${{ github.event.pull_request.state }}
          PR_URL: ${{ github.event.pull_request.html_url }}
