name: Send Slack Notification about new Autodocs PR
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  main:
    if:  startsWith(github.head_ref, 'create-pull-request/')
    runs-on: ubuntu-latest
    steps:
      - name: "Send notification to Slack"
        uses: chainguard-dev/deved-autodocs@1.0.6
        with:
          command: notify pullrequest
          pr_number: ${{ github.event.pull_request.number }}
